print("Goodbye World!")
#print("Hello Again")
#print("I like typing this.")
#print('Yay, this is fun.')
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print("Another line")
